/**
 * POST /api/webhooks/stripe
 *
 * Handles Stripe checkout.session.completed:
 *  1. Creates Order with status PAID + erpSyncStatus=pending_erp_sync
 *  2. Tries to sync to ERP immediately via POST /api/orders
 *  3a. Success → status=PROCESSING, store ESH number + invoice, send confirmation email WITH invoice PDF
 *  3b. Failure → keep status PAID, erpSyncStatus=pending_erp_sync, send ack email without invoice
 *  4. Deducts stock, clears cart
 *
 * GDPR: logs use order IDs only — no customer PII in log output.
 * § 28 ZDPH: invoice is generated by ERP immediately upon payment receipt.
 */

import { NextRequest, NextResponse } from 'next/server'
import { stripe, getStripeWebhookSecret } from '@/lib/stripe'
import { db } from '@/lib/db'
import { sendEmail } from '@/lib/email/send'
import { OrderConfirmationWithInvoice, OrderConfirmationAck } from '@/lib/email/templates/OrderConfirmation'
import { NewOrderNotification } from '@/lib/email/templates/NewOrderNotification'
import { getErpConfig, syncOrderToErp } from '@/lib/erp'
import type Stripe from 'stripe'

export const dynamic = 'force-dynamic'

// Stripe webhooks must consume raw body
export async function POST(req: NextRequest) {
  const body      = await req.text()
  const signature = req.headers.get('stripe-signature')

  if (!signature) {
    return NextResponse.json({ error: 'Missing signature' }, { status: 400 })
  }

  let webhookSecret: string
  try {
    webhookSecret = getStripeWebhookSecret()
  } catch {
    console.error('[Stripe] STRIPE_WEBHOOK_SECRET is not configured')
    return NextResponse.json({ error: 'Webhook not configured' }, { status: 500 })
  }

  let event: Stripe.Event
  try {
    event = stripe.webhooks.constructEvent(body, signature, webhookSecret)
  } catch (err: any) {
    return NextResponse.json({ error: `Webhook Error: ${err.message}` }, { status: 400 })
  }

  if (event.type !== 'checkout.session.completed') {
    return NextResponse.json({ received: true })
  }

  // From this point on: always return 200 to Stripe — retries are handled by our own cron
  try {

  const session      = event.data.object as Stripe.Checkout.Session

  // H3: Verify payment was actually successful before fulfilling the order.
  // checkout.session.completed fires even for unpaid sessions (e.g. bank transfers
  // pending). Only fulfil when payment_status === 'paid'.
  if (session.payment_status !== 'paid') {
    console.warn('[Stripe] checkout.session.completed but payment_status is not paid:', session.id, session.payment_status)
    return NextResponse.json({ received: true })
  }

  const userId       = session.metadata?.userId || null
  const guestEmail   = session.metadata?.guestEmail || null
  const guestName    = session.metadata?.guestName  || null
  const guestPhone   = session.metadata?.guestPhone || null
  const itemsRaw     = session.metadata?.items
  const deliveryType = (session.metadata?.deliveryType ?? 'COURIER') as 'COURIER' | 'PICKUP_IN_STORE' | 'DPD_HOME' | 'DPD_PICKUP' | 'ZASILKOVNA_HOME' | 'ZASILKOVNA_PICKUP'
  const addressId    = session.metadata?.addressId || null

  if ((!userId && !guestEmail) || !itemsRaw) return NextResponse.json({ received: true })

  // ── Resolve order items ─────────────────────────────────────────────────────
  const rawItems: { v: string; q: number }[] = JSON.parse(itemsRaw)
  const variants = await db.productVariant.findMany({
    where: { id: { in: rawItems.map(i => i.v) } },
    include: { product: true },
  })
  const variantMap = new Map(variants.map(v => [v.id, v]))

  const items = rawItems.map(i => {
    const variant = variantMap.get(i.v)
    return {
      variantId:    i.v,
      productId:    variant?.productId ?? '',
      productName:  variant?.product?.name ?? 'Product',
      variantLabel: variant?.name ?? '',
      quantity:     i.q,
      unitPrice:    Math.round(Number(variant?.price ?? 0) * 100), // haléře — price WITH VAT per variant pack
      erpProductId: variant?.erpProductId ?? null,
      variantValue: Number(variant?.variantValue ?? null),   // e.g. 3 for a "3g" variant
      variantUnit:  variant?.variantUnit ?? null,
      vatRate:      Number(variant?.product?.vatRate ?? 21),
    }
  })

  const totalAmount    = session.amount_total ?? 0
  const shippingAmount = session.shipping_cost?.amount_total ?? 0
  const subtotalAmount = totalAmount - shippingAmount

  // ── Idempotency check ──────────────────────────────────────────────────────
  // The success page may have created the order first (as PAID, pending_erp_sync).
  // If fully synced → nothing to do. If not yet synced → use the existing order
  // and proceed with ERP sync (skip creation).
  const existingOrder = await db.order.findUnique({
    where:   { stripeSessionId: session.id },
    include: { items: true, address: true },
  })

  if (existingOrder?.erpSyncStatus === 'synced' && existingOrder?.stockDeducted && existingOrder?.emailSent) {
    console.log(`[Stripe] Already fully processed — skipping, orderId=${existingOrder.id}`)
    return NextResponse.json({ received: true })
  }

  // ── Create order (or reuse existing from success-page fallback) ─────────────
  let order: any
  if (existingOrder) {
    console.log(`[Stripe] Order created by success page, proceeding with ERP sync, orderId=${existingOrder.id}`)
    order = existingOrder
  } else {
    order = await db.order.create({
      data: {
        userId: userId || null,
        guestEmail: userId ? null : guestEmail,
        guestName:  userId ? null : guestName,
        guestPhone: userId ? null : guestPhone,
        addressId: addressId || null,
        stripeSessionId:       session.id,
        stripePaymentIntentId: typeof session.payment_intent === 'string' ? session.payment_intent : null,
        status:          'PAID',
        paidAt:          new Date(),
        erpSyncStatus:   'pending_erp_sync',
        deliveryType,
        currency:        (session.currency ?? 'czk').toUpperCase(),
        totalAmount,
        subtotalAmount,
        shippingAmount,
        pickupPointId:      session.metadata?.pickupPointId      || null,
        pickupPointName:    session.metadata?.pickupPointName    || null,
        pickupPointAddress: session.metadata?.pickupPointAddress || null,
        // Billing address snapshot — only set when user chose a different billing address
        billingName:    session.metadata?.billingName    || null,
        billingCompany: session.metadata?.billingCompany || null,
        billingIco:     session.metadata?.billingIco     || null,
        billingStreet:  session.metadata?.billingLine1   || null,
        billingCity:    session.metadata?.billingCity    || null,
        billingZip:     session.metadata?.billingPostal  || null,
        billingCountry: session.metadata?.billingCountry || null,
        items: {
          create: items.map(item => ({
            productId:    item.productId,
            variantId:    item.variantId,
            productName:  item.productName,
            variantLabel: item.variantLabel,
            quantity:     item.quantity,
            unitPrice:    item.unitPrice,
          })),
        },
      },
      include: { items: true, address: true },
    })
    console.log(`[Stripe] Order created orderId=${order.id}`)
  }

  // ── Load user for email + ERP sync ──────────────────────────────────────────
  const user = userId
    ? await db.user.findUnique({ where: { id: userId }, select: { id: true, name: true, email: true, phone: true } })
    : null

  // Effective contact info (user or guest)
  const contactEmail = user?.email ?? guestEmail ?? null
  const contactName  = user?.name  ?? guestName  ?? null
  const contactPhone = user?.phone ?? guestPhone ?? null

  // Prefer address already loaded with the order; fallback to DB lookup; then guest metadata
  let addr: { fullName: string; line1: string; line2?: string | null; city: string; postalCode: string; country: string } | null =
    order.address ?? null
  if (!addr && addressId) {
    addr = await db.address.findUnique({ where: { id: addressId } })
  }
  // For guest home delivery: rebuild addr from metadata
  if (!addr && session.metadata?.guestShippingLine1) {
    addr = {
      fullName:   session.metadata.guestShippingName  || contactName || '',
      line1:      session.metadata.guestShippingLine1,
      city:       session.metadata.guestShippingCity  || '',
      postalCode: session.metadata.guestShippingPostal || '',
      country:    session.metadata.guestShippingCountry || 'CZ',
    }
  }

  // ── Try ERP sync (Phase 1, steps 3-5) ──────────────────────────────────────
  let erpSynced = false
  try {
    const erpConfig = await getErpConfig()
    if (!erpConfig) {
      console.warn(`[ERP] Not configured — skipping sync for orderId=${order.id}`)
    } else {
      // Build address string for ERP
      const streetLine = addr
        ? [addr.fullName, addr.line1, addr.line2].filter(Boolean).join(', ')
        : 'Neuvedena'
      const cityLine   = addr?.city       || 'Neuvedeno'
      const zipLine    = addr?.postalCode || '00000'
      const country    = addr?.country   || 'CZ'

      // Convert haléře → Kč (CZK integer from Stripe / 100 = Kč)
      const totalCzk    = totalAmount / 100
      const subtotalCzk = subtotalAmount / 100

      const erpItems = items.map(item => {
        // item.unitPrice is in haléře (price WITH VAT per pack).
        // We always send quantity = ordered packs (e.g. 1) with unit "ks".
        // The variant label is appended to the product name so the invoice reads
        // "CBD Olej — 5g  ×1  @850 Kč" — clear and unambiguous.
        // Physical units for stock deduction are handled by the delivery note.
        const unitPriceKc      = item.unitPrice / 100
        const vatRate          = item.vatRate
        const unitPriceCzk     = Math.round((unitPriceKc / (1 + vatRate / 100)) * 100) / 100

        const erpName = item.variantLabel ? `${item.productName} — ${item.variantLabel}` : item.productName
        return {
          sku:          item.erpProductId ?? undefined,
          name:         erpName,
          quantity:     item.quantity,   // počet balení (ks), nikdy fyzické gramy
          unit:         'ks',
          unitPriceCzk,
          vatRate,
        }
      })

      // Shipping as a line item so ERP totals match the Stripe charge
      const shippingCzk = shippingAmount / 100
      if (shippingCzk > 0) {
        erpItems.push({
          sku:          undefined,
          name:         'Doprava',
          quantity:     1,
          unit:         'ks',
          unitPriceCzk: Math.round(shippingCzk / 1.21 * 100) / 100,
          vatRate:      21,
        })
      }

      const paymentRef = typeof session.payment_intent === 'string'
        ? session.payment_intent
        : session.id

      // Derive carrier from deliveryType
      const pickupCarrier: string =
        deliveryType === 'ZASILKOVNA_PICKUP' ? 'zasilkovna' :
        deliveryType === 'DPD_PICKUP'        ? 'dpd'        : ''

      const syncResult = await syncOrderToErp({
        eshopOrderId:     order.id,    // cuid — UUID-like, used as idempotency key
        items:            erpItems,
        customer: {
          name:  contactName  || contactEmail || 'Zákazník',
          email: contactEmail || '',
          ...(contactPhone ? { phone: contactPhone } : {}),
          address: {
            street:  streetLine,
            city:    cityLine,
            zip:     zipLine,
            country,
          },
        },
        totalCzk,
        paymentReference: paymentRef,
        paidAt:           new Date().toISOString(),

        // Shipping method — always sent for eshop orders
        shippingMethod: deliveryType,

        // Pickup point — only when a pickup point was selected
        ...(order.pickupPointId ? {
          pickupPoint: {
            id:      order.pickupPointId,
            name:    order.pickupPointName    || '',
            address: order.pickupPointAddress || '',
            carrier: pickupCarrier,
          },
        } : {}),

        // Billing address — only when customer explicitly provided a different billing address
        ...(order.billingName ? {
          billingAddress: {
            name:    order.billingName,
            company: order.billingCompany || null,
            ico:     order.billingIco     || null,
            street:  order.billingStreet  || '',
            city:    order.billingCity    || '',
            zip:     order.billingZip     || '',
            country: order.billingCountry || 'CZ',
          },
        } : {}),
      }, erpConfig)

      // Update order with ERP data → status PROCESSING
      order = await db.order.update({
        where: { id: order.id },
        data: {
          status:           'PROCESSING',
          erpSyncStatus:    'synced',
          erpOrderNumber:   syncResult.erpOrderNumber,
          invoiceNumber:    syncResult.invoiceNumber,
          invoiceUrl:       syncResult.invoicePdfUrl,
          invoicePdfBase64: syncResult.invoicePdfBase64,
          erpSyncAttempts:  1,
        },
        include: { items: true, address: true },
      })

      // Log sync attempt (success)
      await db.erpSyncAttempt.create({
        data: { orderId: order.id, success: true },
      })

      console.log(`[ERP] Sync success orderId=${order.id} erpOrderNumber=${syncResult.erpOrderNumber}`)
      erpSynced = true
    }
  } catch (erpErr: any) {
    // ERP unreachable — log attempt, keep pending_erp_sync
    console.error(`[ERP] Sync failed for orderId=${order.id}:`, erpErr?.message)
    await db.order.update({
      where: { id: order.id },
      data: {
        erpSyncAttempts:  1,
        erpSyncLastError: erpErr?.message ?? 'Unknown error',
      },
    })
    await db.erpSyncAttempt.create({
      data: { orderId: order.id, success: false, error: erpErr?.message },
    })
  }

  // ── Deduct stock (idempotent — only if not already deducted) ───────────────
  // Stock deduction runs BEFORE email (H12) — email is only sent after the
  // stock transaction is confirmed to avoid sending confirmation for orders
  // whose stock could not be reserved (Finding C1, H12).
  // Re-read the order inside a transaction to prevent double deduction from
  // a race between the webhook and the success page (Finding C1).
  try {
    await db.$transaction(async (tx) => {
      const freshOrder = await tx.order.findUnique({
        where:  { id: order.id },
        select: { stockDeducted: true },
      })
      if (freshOrder?.stockDeducted) {
        console.log(`[Stock] Already deducted for orderId=${order.id} — skipping`)
        return
      }

      // H9: verify stock will not go negative before decrementing
      for (const item of items) {
        const variant = await tx.productVariant.findUnique({
          where:  { id: item.variantId },
          select: { stock: true },
        })
        if (!variant) continue
        if (variant.stock < item.quantity) {
          console.error(`[Stock] Insufficient stock for variantId=${item.variantId}: have ${variant.stock}, need ${item.quantity}`)
          throw new Error(`Insufficient stock for variant ${item.variantId}`)
        }
      }

      for (const item of items) {
        await tx.productVariant.update({
          where: { id: item.variantId },
          data:  { stock: { decrement: item.quantity } },
        })
        await tx.stockMovement.create({
          data: {
            variantId: item.variantId,
            type:      'RESERVED',
            quantity:  item.quantity,
            orderId:   order.id,
            reason:    'Order paid',
          },
        })
      }

      await tx.order.update({
        where: { id: order.id },
        data:  { stockDeducted: true },
      })
    })
  } catch (stockErr) {
    console.error(`[Stock] Error for orderId=${order.id}:`, stockErr instanceof Error ? stockErr.message : String(stockErr))
  }

  // ── Send customer email (H12: after stock tx; H13: emailSent idempotency) ───
  // Re-read emailSent to avoid duplicate emails if both webhook and success page run.
  const freshOrderForEmail = await db.order.findUnique({
    where:  { id: order.id },
    select: { emailSent: true },
  })
  if (contactEmail && !freshOrderForEmail?.emailSent) {
    const emailTo = contactEmail as string
    try {
      const firstName    = contactName?.split(' ')[0] ?? 'zákazníku'
      const shippingAddr = addr
        ? { fullName: addr.fullName, line1: addr.line1, city: addr.city, postalCode: addr.postalCode, country: addr.country }
        : undefined

      if (erpSynced && order.erpOrderNumber) {
        // Mail #1: order confirmed with ERP number + invoice PDF attached (§ 28 ZDPH)
        await sendEmail({
          to:          emailTo,
          subject:     `Potvrzení objednávky ${order.erpOrderNumber} — Weedej`,
          emailType:   'orderConfirmation',
          react:       OrderConfirmationWithInvoice({
            name:             firstName,
            orderNumber:      order.erpOrderNumber!,
            items:            items.map(i => ({ productName: i.productName, variantLabel: i.variantLabel, quantity: i.quantity, unitPrice: i.unitPrice })),
            subtotalAmount,
            shippingAmount,
            totalAmount,
            deliveryType,
            shippingAddress:  shippingAddr,
            invoiceNumber:    order.invoiceNumber ?? undefined,
            invoiceAttached:  !!order.invoicePdfBase64,
          }),
          // Attach invoice PDF if available (§ 28 ZDPH — required in mail #1)
          attachments: order.invoicePdfBase64
            ? [{
                filename:    `faktura-${order.invoiceNumber ?? order.erpOrderNumber}.pdf`,
                content:     order.invoicePdfBase64,
                contentType: 'application/pdf',
                encoding:    'base64',
              }]
            : [],
        })
      } else {
        // ERP unavailable — send acknowledgement without ERP number/invoice
        await sendEmail({
          to:        emailTo,
          subject:   'Přijali jsme vaši objednávku — Weedej',
          emailType: 'orderConfirmation',
          react:     OrderConfirmationAck({
            name:            firstName,
            internalOrderId: order.id,
            items:           items.map(i => ({ productName: i.productName, variantLabel: i.variantLabel, quantity: i.quantity, unitPrice: i.unitPrice })),
            subtotalAmount,
            shippingAmount,
            totalAmount,
            deliveryType,
            shippingAddress: shippingAddr,
          }),
        })
      }
      // Mark email sent atomically (H13)
      await db.order.update({ where: { id: order.id }, data: { emailSent: true } })
    } catch (emailErr) {
      console.error(`[Email] Failed for orderId=${order.id}:`, emailErr instanceof Error ? emailErr.message : String(emailErr))
    }
  }

  // ── Admin notification ──────────────────────────────────────────────────────
  try {
    const adminEmailSetting = await db.setting.findUnique({ where: { key: 'orderNotificationEmail' } })
    const adminEmail        = adminEmailSetting?.value ?? process.env.ADMIN_ORDER_EMAIL
    if (adminEmail) {
      await sendEmail({
        to:      adminEmail,
        subject: `Nová objednávka ${order.erpOrderNumber ?? order.id.slice(-8).toUpperCase()} — Weedej`,
        react:   NewOrderNotification({
          orderNumber:   order.erpOrderNumber ?? order.id,
          customerName:  user?.name ?? user?.email ?? 'Unknown',
          customerEmail: user?.email ?? '',
          items:         items.map(i => ({ productName: i.productName, variantLabel: i.variantLabel, quantity: i.quantity, unitPrice: i.unitPrice })),
          subtotalAmount,
          shippingAmount,
          totalAmount,
          deliveryType,
          shippingAddress: addr
            ? { fullName: addr.fullName, line1: addr.line1, city: addr.city, postalCode: addr.postalCode, country: addr.country }
            : undefined,
        }),
      })
    }
  } catch (adminEmailErr) {
    console.error(`[AdminEmail] Failed for orderId=${order.id}:`, adminEmailErr instanceof Error ? adminEmailErr.message : String(adminEmailErr))
  }

  // ── Clear cart ──────────────────────────────────────────────────────────────
  try {
    if (userId) await db.cartItem.deleteMany({ where: { cart: { userId } } })
  } catch (cartErr) {
    console.error(`[Cart] Failed to clear cart for userId=${userId}:`, cartErr instanceof Error ? cartErr.message : String(cartErr))
  }

  return NextResponse.json({ received: true })

  } catch (handlerErr: unknown) {
    // Never let an uncaught error return a non-200 to Stripe — that would cause retries
    console.error('[Stripe] Unhandled webhook error:', handlerErr instanceof Error ? handlerErr.message : String(handlerErr))
    return NextResponse.json({ received: true })
  }
}
